name: ribo_genome
channels:
  - defaults
  - bioconda
  - r
  - conda-forge
dependencies:
  - python=3.7
  - nextflow=19.04.1
  - openjdk=8
  - samtools>=1.4
  - sra-tools>-2.8.1
  - fastqc=0.11.8
  - setuptools
  - pip
  - matplotlib=3.3.4
  - bowtie2=2.3.4.3
  - hisat2=2.2.0
  - pysam=0.16.0.1
  - bedtools=2.27.1
  - cutadapt=1.18
  - pip:
    - numpy==1.21.6
    - pandas==1.3.5
    - scipy==1.5.4
    - umi-tools==1.1.1
    - git+https://github.com/ribosomeprofiling/ribopy.git
    - ./modified_rfcommands
